export const EXTENSION_RECORD: Record<string, string> = {
  pdf: 'PDF',
  csv: 'CSV',
  txt: 'Texto',
  json: 'JSON',
  xml: 'XML',
  xls: 'Excel',
  xlsx: 'Excel',
  ods: 'Hoja de cálculo',
  doc: 'Word',
  docx: 'Word',
  odt: 'Documento',
  ppt: 'PowerPoint',
  pptx: 'PowerPoint',
  zip: 'ZIP',
  rar: 'RAR',
  '7z': '7-Zip',
  png: 'Imagen',
  jpg: 'Imagen',
  jpeg: 'Imagen',
  gif: 'Imagen',
  webp: 'Imagen',
  svg: 'SVG',
  mp4: 'Video',
  mov: 'Video',
  avi: 'Video',
  mp3: 'Audio',
  wav: 'Audio'
};